In [1]:
import numpy as np
pi = np.pi

In [2]:
# # get cumsum matrix of Y given Theta
# def get_cumsum(Y, Theta):
#     costs = np.empty((len(Y), len(Theta)))
#     for i, theta in enumerate(Theta):
#         costs[:, i] = np.sum(np.square(np.minimum(np.abs(Y - theta), 2*pi - np.abs(Y - theta))), axis=1)
#     return np.cumsum(np.vstack([np.zeros((1, costs.shape[1])), costs]), axis=0)

In [3]:
# Y = np.array([[0.1], [0.1], [1.1], [1.1]])
# Y = np.array([[0.1], [0.1], [2.1], [2.1]])
# Y = np.array([[1.1], [1.1], [0.1], [0.1]])
Y = np.array([[0.1], [1.1], [0.1], [0.1]])
Theta = np.array([[0.0], [1.0], [2.0]])

In [4]:
# T = len(Y)
# M = len(Theta)

In [5]:
# C_star = get_cumsum(Y, Theta)

In [6]:
# C_star

In [7]:
# def L_point(t, s):
#     return C_star[t + 1, s] - C_star[t, s]

In [8]:
def geo_d(theta, psi):
    return np.sum(np.square(np.minimum(np.abs(psi - theta), 2*pi - np.abs(psi - theta))).reshape(-1, 1), axis=1)

print(geo_d(Theta[0], Y[0]))
print(geo_d(Theta, Y[0]))

[0.01]
[0.01 0.81 3.61]


In [9]:
# def d(theta, psi):
#     return np.sum(np.square(np.minimum(np.abs(psi - theta), 2*pi - np.abs(psi - theta))))

In [10]:
Theta_test = np.array([[1, 1], [1.5, 1]])
# theta_test = np.array([1, 1])
theta_test = np.array([1.5, 1])

# xxx = 0.1*np.array([np.array_equal(theta, theta_test) for theta in Theta_test]).reshape(-1, 1)
# xxx

np.any(theta_test != Theta_test, axis=1)

array([ True, False])

In [11]:
def apart(Y, Theta, lda):
    theta_star = -1.0 * np.ones(shape=(len(Y) + 1, 1))
    V = np.zeros(len(Y) + 1)
    for t in range(1, len(Y) + 1):
        V_candidates = V[t-1] + geo_d(Theta, Y[t-1]) + lda * np.any(theta_star[t - 1] != Theta, axis=1)
        best_idx = np.argmin(V_candidates)
        theta_star[t] = Theta[best_idx]
        V[t] = V_candidates[best_idx]
    chpnts = np.arange(len(Y) - 1)[np.any(theta_star[2:] != theta_star[1:-1], axis=1)]
    return chpnts, theta_star[1:]

In [12]:
apart(Y, Theta, 0.1)

(array([0, 1]),
 array([[0.],
        [1.],
        [0.],
        [0.]]))

In [13]:
lda = 0.1

theta_star = -1.0 * np.ones(shape=(len(Y) + 1, 1))
# theta_star[0] = -1.0 * np.ones_like(Y[0])
V = np.zeros(len(Y) + 1)

for t in range(1, len(Y) + 1):
    # V = np.zeros(len(Theta))
    # for s, theta in enumerate(Theta):
    #     if theta != theta_star[t - 1]:
    #         V[s] = C[t - 1] + lda + d([theta], Y[t-1])
    #     else:
    #         V[s] = C[t - 1] + d([theta], Y[t-1])
    V_candidates = V[t-1] + geo_d(Theta, Y[t-1]) + lda * np.any(theta_star[t - 1] != Theta, axis=1)
    best_idx = np.argmin(V_candidates)
    theta_star[t] = Theta[best_idx]
    V[t] = V_candidates[best_idx]

    # print
    print(f't = {t}')
    print(f'V_candidates = {V_candidates}')
    print(f'theta_star = {theta_star[:t+1]}')
    print(f'V[{t}] = {V[t]}')
    print("------------------------------")

t = 1
V_candidates = [0.11 0.91 3.71]
theta_star = [[-1.]
 [ 0.]]
V[1] = 0.11000000000000001
------------------------------
t = 2
V_candidates = [1.32 0.22 1.02]
theta_star = [[-1.]
 [ 0.]
 [ 1.]]
V[2] = 0.22000000000000003
------------------------------
t = 3
V_candidates = [0.33 1.03 3.93]
theta_star = [[-1.]
 [ 0.]
 [ 1.]
 [ 0.]]
V[3] = 0.33000000000000007
------------------------------
t = 4
V_candidates = [0.34 1.24 4.04]
theta_star = [[-1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]
V[4] = 0.3400000000000001
------------------------------


In [14]:
# print(theta_star)
# print(theta_star[1:])
# print(np.any(theta_star[2:] != theta_star[1:-1], axis=1))
print(np.arange(len(Y) - 1)[np.any(theta_star[2:] != theta_star[1:-1], axis=1)])

[0 1]


In [15]:
# t = 1
# V = [[0.11]
#  [0.91]
#  [3.71]]
# theta_star = [[-1.]
#  [ 0.]]
# C[1] = 0.11000000000000001
# ------------------------------
# t = 2
# V = [[1.32]
#  [0.22]
#  [1.02]]
# theta_star = [[-1.]
#  [ 0.]
#  [ 1.]]
# C[2] = 0.22000000000000003
# ------------------------------
# t = 3
# V = [[0.33]
#  [1.03]
#  [3.93]]
# theta_star = [[-1.]
#  [ 0.]
#  [ 1.]
#  [ 0.]]
# C[3] = 0.33000000000000007
# ------------------------------
# t = 4
# V = [[0.34]
#  [1.24]
#  [4.04]]
# theta_star = [[-1.]
#  [ 0.]
#  [ 1.]
#  [ 0.]
#  [ 0.]]
# C[4] = 0.3400000000000001
# ------------------------------

In [16]:
lda = 0.1

theta_star = np.zeros(shape=(len(Y) + 1, 1))
theta_star[0] = -1
C = np.zeros(len(Y) + 1)
C[0] = 0

for t in range(1, len(Y) + 1):
    V = np.zeros(len(Theta))
    for s, theta in enumerate(Theta):
        if theta != theta_star[t - 1]:
            V[s] = C[t - 1] + lda + geo_d(theta, Y[t-1])[0]
        else:
            V[s] = C[t - 1] + geo_d(theta, Y[t-1])[0]
    
    best_index = np.argmin(V)
    theta_star[t] = Theta[best_index]
    C[t] = V[best_index]

    # print
    print(f't = {t}')
    print(f'V = {V}')
    print(f'theta_star = {theta_star[:t+1]}')
    print(f'C[{t}] = {C[t]}')
    print("------------------------------")

t = 1
V = [0.11 0.91 3.71]
theta_star = [[-1.]
 [ 0.]]
C[1] = 0.11000000000000001
------------------------------
t = 2
V = [1.32 0.22 1.02]
theta_star = [[-1.]
 [ 0.]
 [ 1.]]
C[2] = 0.22000000000000003
------------------------------
t = 3
V = [0.33 1.03 3.93]
theta_star = [[-1.]
 [ 0.]
 [ 1.]
 [ 0.]]
C[3] = 0.33000000000000007
------------------------------
t = 4
V = [0.34 1.24 4.04]
theta_star = [[-1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]
C[4] = 0.3400000000000001
------------------------------


In [17]:
# for t in range(1, T + 1):
#     for (s, theta) in enumerate(Theta):
#         same = C[t-1][s_prev]
#         changes = [(s_prime, C[t-1][s_prime] + lda) for s_prime in range(M) if s_prime != s_prev]
#         change = min(val for _, val in changes)
#         # C[t][s] = min(same, change) + L_point(t, s)
#         C[t][s] = min(same, change) + d(Y[t-1], Theta[s])

#         print(f"t={t}, s={s_prev}, same = C[{t-1}][{s_prev}] = {same}")
#         for s_prime, val in changes:
#             print(f"    candidate change from s'={s_prime}: C[{t-1}][{s_prime}] + lda = {val}")
#         print(f"    change = {change}")
#         print(f"    C[{t}][{s}] = min({same}, {change}) + L_point({t}, {s}) = {C[t][s]}\n")
    
#     # s_prev = np.argmin(C[t])
#     print(f's_prev = {s_prev}')

#     theta_star[t] = Theta[np.argmin(C[t])].item()
#     print(f"theta_star[{t}] = argmin(C[{t}]) = {theta_star[t]}")
#     print("--------------------------------------------------------------")