In [1]:
import numpy as np

pi = np.pi

In [2]:
def d2(theta, psi):
    diff = np.abs(psi - theta)
    return np.sum(np.square(np.minimum(diff, 2*pi - diff)))

In [3]:
def apart(y, Theta, lda):
    T = y.shape[0]
    M = Theta.shape[0]

    V = np.zeros((T + 1, M))                        # best cost upto time t and end with level k
    tau = -1 * np.ones((T + 1, M), dtype=np.int32)  # best last time t to change if end with level k
    pathVec = -1 * np.ones((T), dtype=np.int32)     # best last change location upto time t

    best_prev = 0
    for t in range(1, T + 1):
        best_k = 0
        for k in range(M):
            V[t][k]   = V[t - 1][k]
            tau[t][k] = tau[t - 1][k]
            if best_prev + lda < V[t - 1][k]:
                V[t][k]   = best_prev + lda
                tau[t][k] = t - 2

            V[t][k] = V[t][k] + d2(Theta[k], y[t-1])
            
            if(V[t][k] < V[t][best_k]):
                best_k = k

        best_prev = V[t][best_k]
        pathVec[t-1] = tau[t][best_k]

    return V, pathVec

signal = np.array([2, 2, 2, 0.5, 0, 2*pi-0.5]).reshape((-1, 1))
Theta = np.array([2, 0]).reshape((-1, 1))
penalty = 0.1

V, pathVec = apart(signal, Theta, penalty)
print(V)
print(pathVec)

[[0.   0.  ]
 [0.   4.  ]
 [0.   4.1 ]
 [0.   4.1 ]
 [2.25 0.35]
 [4.45 0.35]
 [6.7  0.6 ]]
[-1 -1 -1  2  2  2]


In [11]:
def circular_mean(segment):
    sin_sum = np.mean(np.sin(segment), axis=0)
    print(np.sin(segment))
    print(sin_sum)
    cos_sum = np.mean(np.cos(segment), axis=0)
    print(np.cos(segment))
    print(cos_sum)
    mean_angles = np.arctan2(sin_sum, cos_sum)
    return mean_angles

circular_mean(np.array([2*pi/3, 0, 4*pi/3]).reshape((-1, 1)))

[[ 0.8660254]
 [ 0.       ]
 [-0.8660254]]
[7.40148683e-17]
[[-0.5]
 [ 1. ]
 [-0.5]]
[-7.40148683e-17]


array([2.35619449])